# Generated by Django 3.1.7 on 2023-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230312_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age_number',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
