# Generated by Django 3.1.7 on 2023-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=500)),
                ('product_image', models.CharField(db_index=True, max_length=500)),
                ('price', models.CharField(max_length=500)),
                ('shop_retail', models.CharField(db_index=True, max_length=500)),
            ],
        ),
    ]
