# Generated by Django 3.1.7 on 2023-03-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230312_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
